# Generated by Django 5.2.4 on 2026-02-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(default='partner', max_length=20)),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('owner', 'Property Owner'), ('manager', 'Property Manager'), ('admin', 'Administrator')], max_length=20)),
                ('special_deals_offers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('traveler', 'Traveler')], default='traveler', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
