# Generated by Django 5.2.4 on 2026-02-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_profiles/'),
        ),
    ]
