# Generated by Django 5.2.4 on 2026-02-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_partnerprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome Partners!', max_length=255)),
                ('description', models.TextField(default='Join our network of trusted hospitality partners.')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('commission_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Information',
                'verbose_name_plural': 'Partner Information',
            },
        ),
        migrations.CreateModel(
            name='TravelerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome Travelers!', max_length=255)),
                ('description', models.TextField(default='Discover amazing destinations and experiences.')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traveler Information',
                'verbose_name_plural': 'Traveler Information',
            },
        ),
    ]
