# Generated by Django 5.2.4 on 2026-02-05 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Name of the hotel', max_length=255)),
                ('location', models.CharField(help_text='Specific location/address', max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number_of_rooms', models.PositiveIntegerField(default=1, help_text='Total number of rooms')),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('presidential', 'Presidential')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Hotel description', null=True)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, help_text='Base price per night in USD', max_digits=10)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs/paths for the hotel property')),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenities like ['Free WiFi', 'Pool', 'Gym', 'Restaurant']")),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from travelers (0.00 to 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_ratings', models.PositiveIntegerField(default=0, help_text='Total number of ratings received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(help_text='Partner user who owns this hotel', on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-created_at'],
            },
        ),
    ]
