# Generated by Django 5.2.4 on 2026-02-05 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission rate percentage (1.00% to 10.00%)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
