# Generated by Django 5.2.10 on 2026-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status', max_length=20),
        ),
    ]
