# Generated by Django 5.2.4 on 2026-02-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_is_approved'),
        ('hotel', '0003_hotel_rejection_reason'),
    ]

    operations = [
    ]
