# Generated by Django 5.0.14 on 2026-02-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_is_approved'),
        ('hotel', '0003_hotel_rejection_reason'),
    ]

    operations = [
    ]
