# Generated by Django 5.2.4 on 2026-02-08 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_merge_20260208_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (1.00% to 100.00%)', max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('special_perks', models.JSONField(blank=True, default=list, help_text="List of special perks like ['Free breakfast', 'Late checkout', 'Spa credit $50']")),
                ('valid_until', models.DateField(help_text='Offer valid until this date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offer is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel this offer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
