# Generated by Django 5.2.10 on 2026-02-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_merge_20260211_1402'),
        ('hotel', '0005_specialoffer'),
    ]

    operations = [
    ]
