# Generated by Django 5.2.10 on 2026-02-15 10:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_merge_0004_merge_20260211_1402_0005_specialoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(help_text='Check-in date')),
                ('check_out_date', models.DateField(help_text='Check-out date')),
                ('number_of_guests', models.PositiveIntegerField(default=1, help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night from hotel', max_digits=10)),
                ('number_of_nights', models.PositiveIntegerField(default=1, help_text='Number of nights')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage if any', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount in currency', max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price after discount', max_digits=12)),
                ('special_perks', models.JSONField(blank=True, default=list, help_text="List of special perks included ['Free parking', 'Welcome cocktail', 'Late checkout']")),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Booking status', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Special requests from the traveler', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.hotel')),
                ('traveler', models.ForeignKey(help_text='Traveler who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
