from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from hotel.models import Hotel
from decimal import Decimal
import json


class Command(BaseCommand):
    help = 'Load hotels from JSON data'

    def handle(self, *args, **options):
        # Get or create the partner user
        partner, created = User.objects.get_or_create(
            username='user',
            defaults={
                'email': 'user@example.com',
                'first_name': 'Partner',
                'last_name': 'User'
            }
        )
        
        if created:
            self.stdout.write(self.style.SUCCESS('Created new partner user: user'))
        else:
            self.stdout.write(self.style.SUCCESS('Using existing partner user: user'))

        # Hotel data
        hotels_data = [
            {
                "id": 1,
                "partner_name": "user",
                "hotel_name": "Little National Hotel Sydney",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["rooftop bar and lounge"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.7",
                "total_ratings": 1601,
            },
            {
                "id": 2,
                "partner_name": "user",
                "hotel_name": "Song Hotel Sydney",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["breakfast included"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 261,
            },
            {
                "id": 3,
                "partner_name": "user",
                "hotel_name": "The Star Grand Hotel",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.3",
                "total_ratings": 2340,
            },
            {
                "id": 4,
                "partner_name": "user",
                "hotel_name": "QT Sydney",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 4229,
            },
            {
                "id": 5,
                "partner_name": "user",
                "hotel_name": "Zagame's House",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.9",
                "total_ratings": 497,
            },
            {
                "id": 6,
                "partner_name": "user",
                "hotel_name": "Emporium Hotel South Bank",
                "description": None,
                "location": "Brisbane Brisbane Region Queensland",
                "city": "Brisbane",
                "country": "Australia",
                "amenities": ["rooftop infinity pool"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.8",
                "total_ratings": 1408,
            },
            {
                "id": 7,
                "partner_name": "user",
                "hotel_name": "Royal On The Park Hotel & Suites",
                "description": None,
                "location": "Brisbane Brisbane Region Queensland",
                "city": "Brisbane",
                "country": "Australia",
                "amenities": ["pool", "spa", "gym"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.4",
                "total_ratings": 3479,
            },
            {
                "id": 8,
                "partner_name": "user",
                "hotel_name": "Pensione Hotel Perth",
                "description": None,
                "location": "Perth Greater Perth Western Australia",
                "city": "Perth",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.3",
                "total_ratings": 1991,
            },
            {
                "id": 9,
                "partner_name": "user",
                "hotel_name": "Point Hotel",
                "description": None,
                "location": "Brisbane Brisbane Region Queensland",
                "city": "Brisbane",
                "country": "Australia",
                "amenities": ["rooftop bar"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 1848,
            },
            {
                "id": 10,
                "partner_name": "user",
                "hotel_name": "Dorsett Melbourne",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["indoor pool", "sauna", "steam room", "gym"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 402,
            },
            {
                "id": 11,
                "partner_name": "user",
                "hotel_name": "The Darling",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["spa", "pool"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 2094,
            },
            {
                "id": 12,
                "partner_name": "user",
                "hotel_name": "Four Seasons Hotel Sydney",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["breakfast included"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.4",
                "total_ratings": 8998,
            },
            {
                "id": 13,
                "partner_name": "user",
                "hotel_name": "Grand Chancellor Hotel Hobart",
                "description": None,
                "location": "Hobart Greater Hobart Tasmania",
                "city": "Hobart",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 7259,
            },
            {
                "id": 14,
                "partner_name": "user",
                "hotel_name": "Quest East Perth",
                "description": None,
                "location": "Perth Greater Perth Western Australia",
                "city": "Perth",
                "country": "Australia",
                "amenities": ["rooftop bar"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 892,
            },
            {
                "id": 15,
                "partner_name": "user",
                "hotel_name": "Wildlife Retreat At Taronga",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["breakfast included"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.7",
                "total_ratings": 1267,
            },
            {
                "id": 16,
                "partner_name": "user",
                "hotel_name": "YHA Sydney Harbour",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 1312,
            },
            {
                "id": 17,
                "partner_name": "user",
                "hotel_name": "Rydges Melbourne",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["rooftop pool"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 503,
            },
            {
                "id": 18,
                "partner_name": "user",
                "hotel_name": "The Grace Sydney",
                "description": None,
                "location": "Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.4",
                "total_ratings": 8896,
            },
            {
                "id": 19,
                "partner_name": "user",
                "hotel_name": "Avenue Hotel Canberra",
                "description": None,
                "location": "Canberra Australian Capital Territory",
                "city": "Canberra",
                "country": "Australia",
                "amenities": ["free parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 3627,
            },
            {
                "id": 20,
                "partner_name": "user",
                "hotel_name": "RACV Royal Pines Resort Gold Coast",
                "description": None,
                "location": "Benowa Gold Coast Queensland",
                "city": "Gold Coast",
                "country": "Australia",
                "amenities": ["golf courses", "spa", "pool", "sports facilities"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 1992,
            },
            {
                "id": 21,
                "partner_name": "user",
                "hotel_name": "Quest Docklands",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["fullyequipped kitchens", "large balconies"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 1860,
            },
            {
                "id": 22,
                "partner_name": "user",
                "hotel_name": "Adina Apartment Hotel Brisbane",
                "description": None,
                "location": "Brisbane Brisbane Region Queensland",
                "city": "Brisbane",
                "country": "Australia",
                "amenities": ["breakfast included"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 682,
            },
            {
                "id": 23,
                "partner_name": "user",
                "hotel_name": "Treasury On Collins Melbourne",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["kitchenette", "washer/dryer"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.8",
                "total_ratings": 2198,
            },
            {
                "id": 24,
                "partner_name": "user",
                "hotel_name": "Lanson Place Parliament Gardens, Melbourne",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["spa", "gym", "lap pool"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.8",
                "total_ratings": 194,
            },
            {
                "id": 25,
                "partner_name": "user",
                "hotel_name": "Quest On Franklin",
                "description": None,
                "location": "Adelaide Greater Adelaide South Australia",
                "city": "Adelaide",
                "country": "Australia",
                "amenities": ["well-equipped kitchens", "laundry facilities"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 1521,
            },
            {
                "id": 26,
                "partner_name": "user",
                "hotel_name": "The StandardX, Melbourne",
                "description": None,
                "location": "Fitzroy Yarra Greater Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["rooftop bar"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.8",
                "total_ratings": 201,
            },
            {
                "id": 27,
                "partner_name": "user",
                "hotel_name": "Quest Bella Vista",
                "description": None,
                "location": "Bella Vista The Hills Shire Greater Sydney New South Wales",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["onsite parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.4",
                "total_ratings": 1073,
            },
            {
                "id": 28,
                "partner_name": "user",
                "hotel_name": "Ovolo Brisbane, Fortitude Valley",
                "description": None,
                "location": "Brisbane Brisbane Region Queensland",
                "city": "Brisbane",
                "country": "Australia",
                "amenities": ["rooftop pool", "gym", "spa baths", "complimentary mini bar"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.7",
                "total_ratings": 1744,
            },
            {
                "id": 29,
                "partner_name": "user",
                "hotel_name": "Loch Ard Motor Inn",
                "description": None,
                "location": "Port Campbell Victoria",
                "city": "Port Campbell",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.5",
                "total_ratings": 683,
            },
            {
                "id": 30,
                "partner_name": "user",
                "hotel_name": "Quest Newquay",
                "description": None,
                "location": "Melbourne Victoria",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "4.6",
                "total_ratings": 949,
            },
            {
                "id": 31,
                "partner_name": "user",
                "hotel_name": "Landmark Resort",
                "description": None,
                "location": "Mooloolaba, QLD, Australia",
                "city": "Mooloolaba",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking", "Outdoor pool", "Fitness center", "Sauna", "Hot tub", "Children's pool", "Rooftop terrace"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.5",
                "total_ratings": 2548,
            },
            {
                "id": 32,
                "partner_name": "user",
                "hotel_name": "Mantra Mooloolaba Beach",
                "description": None,
                "location": "Mooloolaba, QLD, Australia",
                "city": "Mooloolaba",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.3",
                "total_ratings": 2829,
            },
            {
                "id": 33,
                "partner_name": "user",
                "hotel_name": "Mantra Lorne",
                "description": None,
                "location": "Lorne, VIC, Australia",
                "city": "Lorne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "7.9",
                "total_ratings": 3207,
            },
            {
                "id": 34,
                "partner_name": "user",
                "hotel_name": "Hyatt Regency Sydney",
                "description": None,
                "location": "Sydney, NSW, Australia",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.3",
                "total_ratings": 3902,
            },
            {
                "id": 35,
                "partner_name": "user",
                "hotel_name": "The Langham Melbourne",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.9",
                "total_ratings": 3042,
            },
            {
                "id": 36,
                "partner_name": "user",
                "hotel_name": "Sydney Harbour Marriott Hotel at Circular Quay",
                "description": None,
                "location": "Sydney, NSW, Australia",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.6",
                "total_ratings": 3141,
            },
            {
                "id": 37,
                "partner_name": "user",
                "hotel_name": "Crown Metropol Melbourne",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.3",
                "total_ratings": 2834,
            },
            {
                "id": 38,
                "partner_name": "user",
                "hotel_name": "DoubleTree by Hilton Melbourne Flinders Street",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.6",
                "total_ratings": 1977,
            },
            {
                "id": 39,
                "partner_name": "user",
                "hotel_name": "Hilton Surfers Paradise",
                "description": None,
                "location": "Surfers Paradise, QLD, Australia",
                "city": "Surfers Paradise",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.3",
                "total_ratings": 3344,
            },
            {
                "id": 40,
                "partner_name": "user",
                "hotel_name": "Wrest Point",
                "description": None,
                "location": "Hobart, TAS, Australia",
                "city": "Hobart",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": "8.6",
                "total_ratings": 3636,
            },
            {
                "id": 41,
                "partner_name": "user",
                "hotel_name": "Outrigger Burleigh",
                "description": None,
                "location": "Miami, QLD, Australia",
                "city": "Miami",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 42,
                "partner_name": "user",
                "hotel_name": "The Ritz-Carlton, Perth",
                "description": None,
                "location": "Perth, WA, Australia",
                "city": "Perth",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 43,
                "partner_name": "user",
                "hotel_name": "The Star Grand at The Star Gold Coast",
                "description": None,
                "location": "Broadbeach, QLD, Australia",
                "city": "Broadbeach",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 44,
                "partner_name": "user",
                "hotel_name": "The Island Gold Coast",
                "description": None,
                "location": "Surfers Paradise, QLD, Australia",
                "city": "Surfers Paradise",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 45,
                "partner_name": "user",
                "hotel_name": "Great Southern Hotel Perth",
                "description": None,
                "location": "Perth, WA, Australia",
                "city": "Perth",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 46,
                "partner_name": "user",
                "hotel_name": "Fairmont Resort Blue Mountains - MGallery",
                "description": None,
                "location": "Leura, NSW, Australia",
                "city": "Leura",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 47,
                "partner_name": "user",
                "hotel_name": "Sea World Resort",
                "description": None,
                "location": "Main Beach, QLD, Australia",
                "city": "Main Beach",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 48,
                "partner_name": "user",
                "hotel_name": "NOAH'S on the beach",
                "description": None,
                "location": "Newcastle, NSW, Australia",
                "city": "Newcastle",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 49,
                "partner_name": "user",
                "hotel_name": "Meriton Suites Southport",
                "description": None,
                "location": "Southport, QLD, Australia",
                "city": "Southport",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 50,
                "partner_name": "user",
                "hotel_name": "Sofitel Sydney Darling Harbour",
                "description": None,
                "location": "Sydney, NSW, Australia",
                "city": "Sydney",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 51,
                "partner_name": "user",
                "hotel_name": "Crown Towers Perth",
                "description": None,
                "location": "Burswood, WA, Australia",
                "city": "Burswood",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 52,
                "partner_name": "user",
                "hotel_name": "The Olsen Melbourne - Art Series",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 53,
                "partner_name": "user",
                "hotel_name": "Imperial Hotel Gold Coast - Islander Hotel Trading Pty Ltd",
                "description": None,
                "location": "Main Beach, QLD, Australia",
                "city": "Main Beach",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 54,
                "partner_name": "user",
                "hotel_name": "Carrington Hotel",
                "description": None,
                "location": "Katoomba, NSW, Australia",
                "city": "Katoomba",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 55,
                "partner_name": "user",
                "hotel_name": "DoubleTree by Hilton Perth Northbridge",
                "description": None,
                "location": "Perth, WA, Australia",
                "city": "Perth",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 56,
                "partner_name": "user",
                "hotel_name": "City Square Motel",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Airport shuttle"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 57,
                "partner_name": "user",
                "hotel_name": "Great Southern Hotel Melbourne",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 58,
                "partner_name": "user",
                "hotel_name": "Paradise Island Resort",
                "description": None,
                "location": "Surfers Paradise, QLD, Australia",
                "city": "Surfers Paradise",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 59,
                "partner_name": "user",
                "hotel_name": "ibis budget Melbourne CBD",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 60,
                "partner_name": "user",
                "hotel_name": "Harrigan's Hunter Valley",
                "description": None,
                "location": "Pokolbin, NSW, Australia",
                "city": "Pokolbin",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 61,
                "partner_name": "user",
                "hotel_name": "Space Hotel",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 62,
                "partner_name": "user",
                "hotel_name": "Cairns Colonial Club Resort",
                "description": None,
                "location": "Cairns, QLD, Australia",
                "city": "Cairns",
                "country": "Australia",
                "amenities": ["Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 63,
                "partner_name": "user",
                "hotel_name": "Best Western Plus The Tudor-Box Hill",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi", "Parking"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 64,
                "partner_name": "user",
                "hotel_name": "Atlantis Hotel Melbourne",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 65,
                "partner_name": "user",
                "hotel_name": "Ibis Sydney Thornleigh",
                "description": None,
                "location": "Sydney, NSW, Australia",
                "city": "Sydney",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 66,
                "partner_name": "user",
                "hotel_name": "Hotel Grand Chancellor Melbourne",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 67,
                "partner_name": "user",
                "hotel_name": "Broadbeach Savannah Resort",
                "description": None,
                "location": "Broadbeach, QLD, Australia",
                "city": "Broadbeach",
                "country": "Australia",
                "amenities": [],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
            {
                "id": 68,
                "partner_name": "user",
                "hotel_name": "The Victoria Hotel",
                "description": None,
                "location": "Melbourne, VIC, Australia",
                "city": "Melbourne",
                "country": "Australia",
                "amenities": ["Pool", "Free Wi-Fi"],
                "images": [],
                "room_type": "standard",
                "number_of_rooms": 1,
                "average_rating": None,
                "total_ratings": None,
            },
        ]

        # Create hotels
        created_count = 0
        skipped_count = 0
        
        for hotel_data in hotels_data:
            hotel_name = hotel_data.get('hotel_name')
            
            # Check if hotel already exists
            if Hotel.objects.filter(hotel_name=hotel_name, partner=partner).exists():
                self.stdout.write(f'  ⊘ Hotel "{hotel_name}" already exists - skipping')
                skipped_count += 1
                continue
            
            # Calculate average rating as float or use 0.00
            avg_rating = hotel_data.get('average_rating')
            if avg_rating is None:
                avg_rating = Decimal('0.00')
            else:
                avg_rating = Decimal(str(avg_rating))
            
            # Get total ratings or use 0
            total_ratings = hotel_data.get('total_ratings')
            if total_ratings is None:
                total_ratings = 0
            
            # Create hotel with reasonable default price (150 USD per night)
            # You can adjust this based on the rating or other factors
            base_price = Decimal('150.00')
            
            try:
                hotel = Hotel.objects.create(
                    partner=partner,
                    hotel_name=hotel_name,
                    description=hotel_data.get('description'),
                    location=hotel_data.get('location', ''),
                    city=hotel_data.get('city', ''),
                    country=hotel_data.get('country', 'Australia'),
                    number_of_rooms=hotel_data.get('number_of_rooms', 1),
                    room_type=hotel_data.get('room_type', 'standard'),
                    base_price_per_night=base_price,
                    amenities=hotel_data.get('amenities', []),
                    images=hotel_data.get('images', []),
                    is_approved='approved',  # Set to approved as requested
                    average_rating=avg_rating,
                    total_ratings=total_ratings,
                )
                self.stdout.write(self.style.SUCCESS(f'  ✓ Created hotel: {hotel_name} (${base_price}/night)'))
                created_count += 1
            except Exception as e:
                self.stdout.write(self.style.ERROR(f'  ✗ Error creating hotel "{hotel_name}": {str(e)}'))

        # Summary
        self.stdout.write(self.style.SUCCESS(f'\n✓ Successfully created {created_count} hotels'))
        if skipped_count > 0:
            self.stdout.write(self.style.WARNING(f'⊘ Skipped {skipped_count} existing hotels'))
